### PR TITLE
modulesync 0.12.8

### PR DESCRIPTION
**Pull request by bbriggs**
Please check the following items before submitting a PR -- thank you!

Note that this project is released with a Contributor Code of Conduct.
By participating in this project you agree to abide by its terms.
[Contributor Code of Conduct](https://voxpupuli.org/coc/).

- [ ] There is no existing PR that addresses this problem
- [ ] Mentioned any existing issues in your commit so they get linked and
  closed once this PR gets merged, i.e: `Closes #1554` in the body of a commit
- [ ] Followed the instructions in the [Contributing](CONTRIBUTING.md) document
- [ ] Ran the unit/spec tests and ensured they still pass
- [ ] Added tests to cover the new behaviour
- [ ] Updated the documentation to match the changes
- [ ] When possible, add an entry to the CHANGELOG file
- [ ] Squashed your PR down to a single commit. You may forego this if the PR
  tries to address multiple issues. Though we prefer one PR per feature/fix,
  sometimes that's not feasible. In that case ensure that a single feature/fix
  and associated tests and documentation is bundled up in one commit

Optional, but extra points:

- [ ] Added tests to ensure the old behaviour cannot accidentally be
  reintroduced

- - -

### CODE REVIEW

**Comment by bastelfreak** [comment]
does anybody have an idea how we can safely manage windows related stuff? Currently we purge half of the Gemfile which is bad :(

**Comment by bastelfreak** [comment]
@bbriggs we should have a look here. maybe also @petems because he is smart!

**Comment by bbriggs** [comment]
We broke everything!

```
/home/travis/.rvm/gems/ruby-2.1.9@global/gems/bundler-1.13.1/lib/bundler/rubygems_integration.rb:336:in `block (2 levels) in replace_gem': rake is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
```

**Comment by bbriggs** [comment]
I think the solution here is to use .sync.yml to specify the whole gemfile since we mangle it pretty badly already.

**Comment by bastelfreak** [comment]
@petems are you interested in helping out here?

**Pull request closed without merging**
