### PR TITLE
Targeted Deprecation Notice of Restart parameter (#120)

### LINKED ISSUE #120: The restart parameter has been deprecated in favor of the puppetlabs reboot module ( https://github.com/puppetlabs/puppetlabs-reboot ). This parameter will be removed in the next release.  (location: C:/ProgramData/PuppetLabs/puppet/cache/lib/puppet/type/windowsfeature.rb:20:in `block (2 levels) in <top (required)>') shows every run
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.3 (2018.1.2)
- Ruby:
- Distribution:
- Module version: 3.2.0

## What are you seeing

Every run on the Puppet Agent displays the following error message 
"The restart parameter has been deprecated in favor of the puppetlabs reboot module ( https://github.com/puppetlabs/puppetlabs-reboot ). This parameter will be removed in the next release.

(location: C:/ProgramData/PuppetLabs/puppet/cache/lib/puppet/type/windowsfeature.rb:20:in `block (2 levels) in <top (required)>')"

## What behaviour did you expect instead
I'd expect this message to show if I was using the restart parameter anywhere.  But I'm not and this message shows up on all of my servers with every run

### PR DESCRIPTION
**Pull request by fiveshotsofespresso**
#### Pull Request (PR) description

Module should only throw a warning if the restart parameter is being used, not anytime a windowsfeature resource is used

#### This Pull Request (PR) fixes the following issues

Fixes #120

### CODE REVIEW

**Comment by wardhus** [comment]
Please merge this. It's a super annoying notice.

**Comment by rismoney** [comment]
any update on this ?

**Comment by wardhus** [comment]
Any news?

**Comment by TraGicCode** [comment]
Hello @fiveshotsofespresso ,

Thanks for contributing to this module.  Everything LGTM 👍

**Pull request merged**
