### PR TITLE
Updated source parameter in provider create

### PR DESCRIPTION
**Pull request by Spartanaco**
https://github.com/voxpupuli/puppet-windowsfeature/issues/80

### CODE REVIEW

**Comment by bbriggs** [comment]
Thanks for the PR, @Spartanaco! Since you mentioned extending the patch with tests in #80, would you mind add those to this as well? You'd be the perfect person to do so.

**Comment by bbriggs** [comment]
Other than that, @bastelfreak and I both think it looks fine.

**Comment by Spartanaco** [comment]
So I made a first attempt at adding some new unit tests for these parameters, I am new to this so I am not sure if it is correct, but it passed the automated testing through Travis-CI I have setup on my fork.

Thanks @bbriggs and @bastelfreak ! :smile:

**Comment by bastelfreak** [comment]
thanks!

**Comment by stealthybox** [comment]
I believe #81 closes this issue.
It's merged pending 2.1.1 release.

**Pull request merged**
